    import type { Metadata } from 'next'
    import { Inter } from 'next/font/google'
    import './globals.css'

    const inter = Inter({ subsets: ['latin'] })

    export const metadata: Metadata = {
    title: 'MCFC Fan Chants',
    description: 'Generated by create next app',
    }

    export default function RootLayout({
    children,
    }: {
    children: React.ReactNode
    }) {
    return (
        <html lang="en">
            <body
            className={`${inter.className} bg-gray-100`}>
                <div
                style={{boxShadow: "0px 0px 10px rgba(50, 50, 50, 0.17);"}}
                className="my-6 mx-48 bg-white">
                    {children}
                </div>
            </body>
        </html>
    )
    }
