import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Nav from '@/components/Nav'
import Heading from '@/components/Heading'
import RoutedText from '@/components/RoutedText'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
title: 'MCFC Fan Chants',
description: 'Generated by create next app',
}

export default function RootLayout({
    children,
    }: {
    children: React.ReactNode
    }) {

    return (
        <html lang="en">
            <body
            className={`${inter.className} bg-gray-100`}>
                <div
                style={{boxShadow: "0px 0px 10px rgba(50, 50, 50, 0.17)"}}
                className="my-6 mx-48 bg-white">
                    <Header />
                    <Nav />
                    <div className="grid grid-cols-5">
                        <div className="col-span-3 m-5 ml-11 mt-10">
                            <div className="mb-10">
                                <Heading
                                color="">
                                    <>
                                        <RoutedText />
                                    </>
                                </Heading>
                                <div 
                                id="margin"
                                className="h-16"></div>
                                {children}
                            </div>
                        </div>
                        <div className="grid grid-cols-1 gap-6 col-span-2 p-10 h-min">
                            <div className="h-64 bg-red-600 opacity-30"></div>
                            <div className="bg-green-600 h-72 opacity-30"></div>
                            <div className="bg-yellow-600 h-24 opacity-30"></div>
                            <div className="bg-blue-600 h-72 opacity-30"></div>
                        </div>
                    </div>
                </div>
            </body>
        </html>
    )
}
